// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASfywb-qJYLnm9-cU0eFZxvSERzR24uAY',
    appId: '1:868062984843:web:415ace6277fe5e2359728e',
    messagingSenderId: '868062984843',
    projectId: 'kcgc-e80ea',
    authDomain: 'kcgc-e80ea.firebaseapp.com',
    storageBucket: 'kcgc-e80ea.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7fIy3nGagDQsbmhr2osggOpUJd-UPUOQ',
    appId: '1:868062984843:android:6c0e01b9343ccfca59728e',
    messagingSenderId: '868062984843',
    projectId: 'kcgc-e80ea',
    storageBucket: 'kcgc-e80ea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtjtPk6a63GCvz8eUn79pc9biw5UtJr_0',
    appId: '1:868062984843:ios:0ef247287a003bfd59728e',
    messagingSenderId: '868062984843',
    projectId: 'kcgc-e80ea',
    storageBucket: 'kcgc-e80ea.appspot.com',
    iosBundleId: 'com.example.kcgcApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtjtPk6a63GCvz8eUn79pc9biw5UtJr_0',
    appId: '1:868062984843:ios:0ef247287a003bfd59728e',
    messagingSenderId: '868062984843',
    projectId: 'kcgc-e80ea',
    storageBucket: 'kcgc-e80ea.appspot.com',
    iosBundleId: 'com.example.kcgcApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASfywb-qJYLnm9-cU0eFZxvSERzR24uAY',
    appId: '1:868062984843:web:0cf695562d67024a59728e',
    messagingSenderId: '868062984843',
    projectId: 'kcgc-e80ea',
    authDomain: 'kcgc-e80ea.firebaseapp.com',
    storageBucket: 'kcgc-e80ea.appspot.com',
  );
}
